UserID = {
	Char1 = {
		FirstName = "Max",
		LastName = "Mustermann",
		Gender = "M",
		DOB = "DD-MM-JJJJ",
		Height = 0,
		Nationality = "",
	},
	Char2 = {
		FirstName = "Max",
		LastName = "Mustermann",
		Gender = "M",
		DOB = "DD-MM-JJJJ",
		Height = 0,
		Nationality = "",
	},
	Char3 = {
		FirstName = "Max",
		LastName = "Mustermann",
		Gender = "M",
		DOB = "DD-MM-JJJJ",
		Height = 0,
		Nationality = "",
	},
}
